/**
 * Business Engine - Recommendation Engine Interfaces
 */

import { PillarId, MaturityBand } from '../assessment-engine/types';
import { ScoreBandKey } from '../rule-database/types';

/**
 * Individual Recommendation Record structure mapped to each Recommendation Code (28 total)
 */
export interface RecommendationEntry {
  recommendationCode: string; // e.g. 'LDR-01', 'OPS-03'
  pillarId: PillarId;
  pillarName: string;
  scoreBand: ScoreBandKey;
  maturityBand: MaturityBand;
  title: string;

  /** Quick actions business owners can execute immediately (Max 3 bullet points) */
  immediateActions: string[];

  /** 30-Day Action Plan: Foundation, Planning, Initial Implementation (Max 3 bullet points) */
  plan30Days: string[];

  /** 60-Day Action Plan: System Implementation, Team Adoption, Process Improvements (Max 3 bullet points) */
  plan60Days: string[];

  /** 90-Day Action Plan: Optimization, Measurement, Scaling (Max 3 bullet points) */
  plan90Days: string[];

  /** Measurable Key Performance Indicators for monitoring progress (Max 3 KPIs) */
  kpis: string[];

  /** Tangible financial and operational results (Max 3 outcomes) */
  expectedOutcomes: string[];

  /** Implementation Effort Rating for realistic prioritization */
  implementationEffort: 'Low' | 'Medium' | 'High';

  /** Estimated Business Impact Rating */
  businessImpact: 'Low' | 'Medium' | 'High';

  /** Prerequisite recommendations or system dependencies */
  dependencies?: string[];
}

/**
 * Full Recommendation Repository Mapping
 */
export type RecommendationCodeDatabase = Record<string, RecommendationEntry>;

/**
 * Evaluated Recommendation Result per Growth Pillar
 */
export interface PillarRecommendationResult {
  pillarId: PillarId;
  pillarName: string;
  score: number;
  scoreBand: ScoreBandKey;
  maturityBand: MaturityBand;
  recommendationCode: string;
  entry: RecommendationEntry;
}

/**
 * Complete Output generated by RecommendationEngine
 */
export interface RecommendationEngineResult {
  overallScore: number;
  maturityBand: MaturityBand;
  primaryFocusPillarId: PillarId;
  primaryFocusCode: string;
  pillarRecommendations: Record<PillarId, PillarRecommendationResult>;

  /** Structured 90-Day Strategic Roadmap */
  roadmap: {
    immediate: { pillarId: PillarId; pillarName: string; code: string; actions: string[] }[];
    day30: { pillarId: PillarId; pillarName: string; code: string; actions: string[] }[];
    day60: { pillarId: PillarId; pillarName: string; code: string; actions: string[] }[];
    day90: { pillarId: PillarId; pillarName: string; code: string; actions: string[] }[];
  };

  /** Core consolidated KPIs to track */
  priorityKPIs: string[];

  /** Consolidated expected business outcomes */
  expectedBusinessOutcomes: string[];
}
